// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: hosts_queries.sql

package database

import (
	"context"
)

const getHosts = `-- name: GetHosts :one
SELECT id, host_name, canonical_name, url, ip, ipv6, location, os, active, last_updated FROM hosts 
Limit ?
Offset ?
`

type GetHostsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetHosts(ctx context.Context, arg GetHostsParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHosts, arg.Limit, arg.Offset)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.HostName,
		&i.CanonicalName,
		&i.Url,
		&i.Ip,
		&i.Ipv6,
		&i.Location,
		&i.Os,
		&i.Active,
		&i.LastUpdated,
	)
	return i, err
}
