// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: host_service_queries.sql

package database

import (
	"context"
	"database/sql"
)

const getHostServices = `-- name: GetHostServices :many
SELECT hs.id, hs.host_id, hs.service_id, hs.active, hs.schedule_number, hs.schedule_unit, hs.last_check, hs.last_updated, hs.status, h.host_name, s.service_name
FROM host_services as hs
JOIN hosts as h ON hs.host_id = h.id
JOIN services as s ON hs.service_id = s.id
WHERE hs.host_id = ?
AND hs.active = 1
`

type GetHostServicesRow struct {
	ID             int64          `json:"id"`
	HostID         sql.NullInt64  `json:"host_id"`
	ServiceID      sql.NullInt64  `json:"service_id"`
	Active         sql.NullInt64  `json:"active"`
	ScheduleNumber sql.NullInt64  `json:"schedule_number"`
	ScheduleUnit   sql.NullString `json:"schedule_unit"`
	LastCheck      sql.NullTime   `json:"last_check"`
	LastUpdated    sql.NullTime   `json:"last_updated"`
	Status         sql.NullString `json:"status"`
	HostName       string         `json:"host_name"`
	ServiceName    sql.NullString `json:"service_name"`
}

func (q *Queries) GetHostServices(ctx context.Context, hostID sql.NullInt64) ([]GetHostServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getHostServices, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHostServicesRow{}
	for rows.Next() {
		var i GetHostServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ServiceID,
			&i.Active,
			&i.ScheduleNumber,
			&i.ScheduleUnit,
			&i.LastCheck,
			&i.LastUpdated,
			&i.Status,
			&i.HostName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
