// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
)

type Host struct {
	ID            int64          `json:"id"`
	HostName      string         `json:"host_name"`
	CanonicalName sql.NullString `json:"canonical_name"`
	Url           sql.NullString `json:"url"`
	Ip            sql.NullString `json:"ip"`
	Ipv6          sql.NullString `json:"ipv6"`
	Location      sql.NullString `json:"location"`
	Os            sql.NullString `json:"os"`
	Active        sql.NullInt64  `json:"active"`
	LastUpdated   sql.NullTime   `json:"last_updated"`
}

type HostService struct {
	ID             int64          `json:"id"`
	HostID         sql.NullInt64  `json:"host_id"`
	ServiceID      sql.NullInt64  `json:"service_id"`
	Active         sql.NullInt64  `json:"active"`
	ScheduleNumber sql.NullInt64  `json:"schedule_number"`
	ScheduleUnit   sql.NullString `json:"schedule_unit"`
	LastCheck      sql.NullTime   `json:"last_check"`
	LastUpdated    sql.NullTime   `json:"last_updated"`
}

type Service struct {
	ID          int64          `json:"id"`
	ServiceName sql.NullString `json:"service_name"`
	Active      sql.NullInt64  `json:"active"`
	Icon        sql.NullString `json:"icon"`
	LastUpdated sql.NullTime   `json:"last_updated"`
}

type User struct {
	ID          int64          `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	UserActive  sql.NullInt64  `json:"user_active"`
	AccessLevel sql.NullInt64  `json:"access_level"`
	Email       sql.NullString `json:"email"`
	Password    sql.NullString `json:"password"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
