// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"context"
)

type Querier interface {
	GetHosts(ctx context.Context, arg GetHostsParams) (Host, error)
}

var _ Querier = (*Queries)(nil)
