// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: service_queries.sql

package database

import (
	"context"
)

const getServices = `-- name: GetServices :one
SELECT id, service_name, active, icon, last_updated FROM services
WHERE active = 1
`

func (q *Queries) GetServices(ctx context.Context) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServices)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Active,
		&i.Icon,
		&i.LastUpdated,
	)
	return i, err
}
