// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user_queries.sql

package database

import (
	"context"
	"database/sql"
)

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT email, password, id 
FROM users 
WHERE email = ?
`

type GetUserForAuthRow struct {
	Email    sql.NullString `json:"email"`
	Password sql.NullString `json:"password"`
	ID       int64          `json:"id"`
}

func (q *Queries) GetUserForAuth(ctx context.Context, email sql.NullString) (GetUserForAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForAuth, email)
	var i GetUserForAuthRow
	err := row.Scan(&i.Email, &i.Password, &i.ID)
	return i, err
}
